apiVersion: v1
kind: ConfigMap
metadata:
  name: thumbnail-config
data:
  MINIO_ENDPOINT: minio
  MINIO_PORT: "9000"
  MINIO_USE_SSL: "false"
  MINIO_ACCESS_KEY: minio
  MINIO_SECRET_KEY: minio123
  MONGO_URL: mongodb://mongodb:27017
