apiVersion: apps/v1
kind: Deployment
metadata:
  name: thumbnail-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thumbnail-api
  template:
    metadata:
      labels:
        app: thumbnail-api
    spec:
      containers:
        - name: api
          image: clevertang/thumbnail-app:latest
          command: [ "npm", "run", "start" ]
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: SERVER_TYPE
              value: server
          envFrom:
            - configMapRef:
                name: thumbnail-config
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi

