apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: thumbnail-api
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: thumbnail.local
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: thumbnail-api
                port:
                  number: 80
            path: /
