apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ingress-nginx-alerts
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  groups:
    - name: ingress-nginx.rules
      rules:
        - alert: High5xxErrorRate
          expr: |
            sum(rate(nginx_ingress_controller_requests{status=~"5.."}[5m]))
            /
            sum(rate(nginx_ingress_controller_requests[5m]))
            > 0.05
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "High 5xx error rate on ingress"
            description: |
              More than 5% of ingress-nginx responses were 5xx in the past 5 minutes.

        - alert: IngressNginxDown
          expr: |
            absent(up{job=~".*nginx.*"} == 1)
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Ingress NGINX appears down"
            description: |
              Prometheus hasn't scraped ingress-nginx metrics for over a minute.
