apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: thumbnail-api
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: thumbnail-api
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /
      interval: 15s
      scheme: http
