grafana:
  adminPassword: prom-operator
  service:
    type: ClusterIP
  ingress:
    enabled: true
    hosts:
      - grafana.local
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    ingressClassName: nginx
    sidecar:
      dashboards:
        enabled: true
        label: grafana_dashboard

    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: nginx
            orgId: 1
            folder: Ingress
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/nginx


prometheus:
  service:
    type: ClusterIP
  ingress:
    enabled: true
    hosts:
      - prometheus.local
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    ingressClassName: nginx

kube-state-metrics:
  enabled: true